### ISSUE TITLE
fossil gen

### ISSUE THREAD

**Issue by vaylor27** [Dumb-Code/ProjectNublar#6]
# TODO: DNA Extraction rates
- [ ] Each has a different chance of DNA extraction, with weathered being 0% and Timeless being 100%
- [ ] Each Type will have a different DNA extraction multiplier which is multiplied by the chance gotten from the tier to get the final chance
- [ ] Some fossils (e.g. feather) can grant multiple types of DNA, though only one type per fossil
- [ ] Some Fossils, Like Ammonite, will grant no DNA
- [ ] Some stones and fossil types will have different chances to get rarer DNA from those fossils that support multiple types of DNA being extracted

# World Generation (I'm Dreading this)
- [ ] Fossils generate in strata based on their time
- [ ] some fossils and stone types generate more often in some biomes
- [ ] Fossils of the same dino and/or formation generate near/next to each other
- [ ] each strata is 3-4 blocks tall
- [ ] some large formations of fossils
- [ ] all fossils in a vein have a chance to drop unidentified fossil

# Fossil Types (other than generic and common types)
- [ ] Rex:
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hell Creek and lance formations
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;83.6-65 mya
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Biomes: hills, forests, taiga, old growth taiga, river, badlands, plains, caves

- [ ] Velociraptor:
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cloverly, Bayan Mandahu, Flaming Cliffs, and Djadochta Formations
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;75-71 mya
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Biomes: desert, badlands, plains, hills, caves, swamps, rivers

- [ ] Brachiosaurus
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tendagruru and Morrison Formation
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;154-150 mya
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;biomes: desert, forest, badlands, plains, hills, caves, swamps, rivers

- [ ] Triceratops
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hell creek and lance formations
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;68-65 mya
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;biomes: hills, forests, taiga, old growth taiga, rivers, badlands, plains, caves

- [ ] Dilophosaurus
- [ ] Kayenta, Wingate, Moenave, and Navajo formations
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;201.3-182.7 mya
- [ ] biomes: desert, badlands, caves, rivers

- [ ]  Gallimimus:
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nemegt Formation
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;73-68 mya
- [ ] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;biomes: desert, badlands, caves, rivers
